accounts/urls.py
from django.urls import path
from .views import SignUpView


urlpatterns = [
    path("signup/", SignUpView.as_view(), name="signup"),
]

answers_app/urls.py
from django.urls import path
from .views import *

urlpatterns = [
    path('question/detail/<int:pk>/answer/create/', AnswersCreateView.as_view(), name='answer_create'),
    
]

config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("accounts/", include("django.contrib.auth.urls")),
    path("accounts/", include("accounts.urls")),
    path('questions/', include('questions_app.urls')),
    path('answers/', include('answers_app.urls')),
]

questions_app/urls.py
from django.urls import path, include
from .views import *

urlpatterns = [
    path('', QuestionListViewSet.as_view(), name="list_question"),
    path('question/detail/<int:pk>', QuestionDetailViewSet.as_view(), name="detail_view"),
]

accounts/models.py
from django.db import models

# Create your models here.

answers_app/models/answers.py
from django.db import models
from django.contrib.auth.models import User


class Answer(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, 
                             verbose_name="Пользователь")
    question_text = models.ForeignKey("questions_app.Question", on_delete=models.CASCADE, 
                                      verbose_name="Текст вопроса")
    answer_text = models.TextField("Текст ответа")
    image_answer = models.ImageField("Фото ответ", upload_to="images/", blank=True)
    video_answer = models.URLField("Видео ответ", max_length=250, blank=True)
    permission = models.BooleanField("Разрешение", default=False)
    date_created = models.DateTimeField("Время добавления ответа", auto_now_add=True)

    class Meta:
        ordering = ["user"]
        verbose_name = "Ответ"
        verbose_name_plural = "Ответы"
    
    def __str__(self) -> str:
        return self.answer_text
    

questions_app/models/questions.py
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User


class Question(models.Model):

    TITLE_CHOICES = (
        ('Технология', 'Технология'),
        ('Наука', 'Наука'),
        ('Исскусство и Литература', 'Исскусство и Литература'),
        ('Здоровье и Медицина', 'Здоровье и Медицина'),
        ('Бизнесс и Финанс', 'Бизнесс и Финанс'),
        ('Путешествие и Туризм', 'Путешествие и Туризм'),
        ('Образование', 'Education'),
        ('Спорт и Фитнес', 'Sports & Fitness'),
        ('Еда и Готовка', 'Food & Cooking'),
        ('Развлечение', 'Entertainment'),
        ('История', 'History'),
        ('Отношения и Знакомства', 'Relationships & Dating'),
        ('Политики и Правительство', 'Politics & Government'),
        ('Окружающая среда и Устойчивость', 'Environment & Sustainability'),
        ('Религия и Духовность', 'Religion & Spirituality'),
        ('Личностное развитие и Саморазвитие', 'Personal Development & Self-Improvement'),
    )

    user = models.ForeignKey(User, on_delete=models.CASCADE, 
                             verbose_name="Пользователь")
    title = models.CharField("Описание", max_length=250)
    question_category = models.CharField(verbose_name="категория", max_length=250, 
                                         choices=TITLE_CHOICES)
    question_text = models.TextField("Текст вопроса")
    date_created = models.DateTimeField("Время добавления вопроса", auto_now_add=True)
    
    class Meta:
        ordering = ["question_text"]
        verbose_name = "Вопрос"
        verbose_name_plural = "Вопросы"
    
    def __str__(self) -> str:
        return self.title
    
    def get_absolute_url(self):
        return reverse('detail_view', kwargs={'pk': self.pk})

answers_app/forms/answer.py
from django import forms
from ..models import Answer
from questions_app.models import Question

class AnswerForm(forms.ModelForm):

    class Meta:

        model = Answer
        # fields = ['answer_text', 'image_answer', 'video_answer']
        fields = ['answer_text']
        widgets = {
            # 'user': forms.Select(attrs={'class': 'form-control'}),
            # 'question_text': forms.Select(attrs={'class': 'form-control'}),
            'answer_text': forms.Textarea(attrs={'class': 'form-control my-custom-class', 'rows': 4}),
            # 'image_answer': forms.ClearableFileInput(attrs={'class': 'form-control'}),
            # 'video_answer': forms.URLInput(attrs={'class': 'form-control'}),
            # 'audio_answer': forms.ClearableFileInput(attrs={'class': 'form-control'}),
        }

questions_app/forms/question.py
from django import forms
from ..models import Question


class QuestionForm(forms.ModelForm):
    title = forms.CharField(label='Question Title')
    
    class Meta:
        model = Question
        fields = ['user', 'title', 'question_category', 'question_text']
        widgets = {
            'question_text': forms.Textarea(attrs={'rows': 4}),
        }

accounts/views.py
from django.contrib.auth.forms import UserCreationForm
from django.urls import reverse_lazy
from django.views.generic import CreateView


class SignUpView(CreateView):
    form_class = UserCreationForm
    success_url = reverse_lazy("login")
    template_name = "registration/signup.html"

answers_app/views/answers.py
from django.views import generic
from django.shortcuts import render, get_object_or_404
from django.urls import reverse

from ..models import Answer
from ..forms import AnswerForm

from questions_app.models import Question

class AnswersCreateView(generic.CreateView):
    model = Answer
    template_name = 'answers/answer_create.html'
    form_class = AnswerForm
    
    def form_valid(self, form):
        question_id = self.kwargs['pk']
        question = get_object_or_404(Question, pk=question_id)
        form.instance.question = question
        form.instance.question_text_id = question_id
        form.instance.user = self.request.user
        return super().form_valid(form)
    
    def get_success_url(self):
        question_id = self.kwargs['pk']
        return reverse('detail_view', kwargs={'pk': question_id})
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        question_id = self.kwargs['pk']
        question = get_object_or_404(Question, pk=question_id)
        context['question'] = question
        context['user'] = self.request.user
        return context

questions_app/views/questions.py
from django.urls import reverse_lazy
from django.views import generic

from ..models import Question
from ..forms import QuestionForm

class QuestionListViewSet(generic.ListView):
    model = Question
    quetion_list = Question.objects.all()
    template_name = 'questions/question.html'


class QuestionDetailViewSet(generic.DetailView):
    model = Question
    context = Question.objects.all()
    template_name = 'questions/question_detail.html'
    context_object_name = 'question'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        question = self.get_object()
        context['question'] = question
        return context

templates/answers/answer_create.html
{% extends "base.html" %}
{% load static %}
{% block content %}

<style>
  .submit-button {
    display: inline-block;
    padding: 10px 20px;
    background-color: #4c5eaf;
    color: white;
    border: none;
    border-radius: 10px;
    font-size: 16px;
    cursor: pointer;
    transition: background-color 0.3s;
  }

  .submit-button:hover {
    background-color: #45a049;
  }

  
    .menu-button {
      display: inline-block;
      padding: 10px 20px;
      background-color: rgb(241, 239, 239);
      color: rgb(14, 13, 13);
      border: none;
      border-radius: 4px;
      font-size: 16px;
      cursor: pointer;
      transition: background-color 0.3s;
      box-shadow: 0 2px 4px rgba(0, 0, 0, 0.3);
      position: fixed;
      top: 20px;
      right: 50px;
    }

    .menu-button:hover {
      background-color: transparent;
    }
  
    .container {
      max-width: 700px; /* Adjust the desired maximum width */
      margin: 0 auto; /* Center the container horizontally */
      padding: 20px;
    }

    .content {
      margin-top: 40px; /* Adjust the margin as needed */
    }

    .my-custom-class {
      background-color: #F0F0F0;
      font-size: 16px;
      border-color: transparent;
    }

    .text-container {
        background-color: rgb(241, 239, 239);
        border-radius: 10px;
        text-align: text;
        padding: 10px 10px;
    }

    .question-text {
        color: grey; /* Set the desired text color */
    }

    .title-text {
        color: black; /* Set the desired text color */
    }

    .return-button {
      display: inline-block;
      padding: 10px 20px;
      background-color: transparent;
      color: rgb(14, 13, 13);
      border: none;
      border-radius: 4px;
      font-size: 16px;
      cursor: pointer;
      transition: background-color 0.3s;
      box-shadow: 0 2px 4px rgba(0, 0, 0, 0.3);
      position: fixed;
      top: 20px;
      left: 50px;
    }

    .return-button:hover {
      background-color: transparent;
    }

  </style>

<body>
  <div class="container">
    <div class="text-container"> Это вопрос в теме "{{question.question_category}}". 
      Пожалуйста, ответственно относитесь к ответам на такие вопросы.</div><br>
    <button class="menu-button">{{user.username}}</button>
    <button class="return-button">
      <a href="{% url 'detail_view' question.id %}">&larr; Назад</a>
    </button>
    <h2 class="title-text">{{ question.title }}</h2>
    <p class="question-text">{{ question.question_text }}</p><br>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
      <button class="submit-button" type="submit">Сохранить</button>
    </form>
  </div>

{% endblock %}

templates/base.html
<!-- base.html -->
<!DOCTYPE html>
<html lang="en">
{% load static %}

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Савол</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <link rel="stylesheet" src="{% static 'css/style_question.css' %}">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.4/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.7.0/jquery.js" integrity="sha512-8Z5++K1rB3U+USaLKG6oO8uWWBhdYsM3hmdirnOEWp8h2B1aOikj5zBzlXs8QOrvY9OxEnD2QDkbSKKpfqcIWw==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
</head>

<body id="body">
    <style>
        body{
            background-color: white;
        }
    </style>
    <main role="main">
        {% block content %}{% endblock %}
    </main>
    <script src="{% static 'js/script.js' %}"></script>
</body>

</html>

templates/questions/question.html
{% extends "base.html" %}

{% block content %}

{% if user.is_authenticated %}
    <p><a href="{% url 'logout' %}">Выйти</a></p>
{% else %}
    <p><a href="{% url 'login' %}">Войти</a></p><br>
    <p><a href="{% url 'signup' %}">Зарегистрироваться</a></p><br>
{% endif %}

<div class="question-list">
    <h1>Список вопросов</h1>
    <ul>
        {% for question in question_list %}
            <li><strong>{{ question.title }}</strong></li>
            <br>{{ question.question_text }}

            {% if user.is_authenticated %}
                <a href="{% url 'detail_view' question.id %}">Подробнее...</a>
            {% endif %}
            <hr>

        {% empty %}
            <li>Нету доступных вопросов.</li>
        {% endfor %}
    </ul>
</div>
{% endblock %}

templates/questions/question_detail.html
{% extends "base.html" %}

{% block content %}

{% load static %}

<div class="question-list">
    <h1>Подробнее</h1>
    {{ question.question_category }}
    <p>Автор: {{ question.user }}</p>
    <h2>{{ question.title }}</h2>
    <p>{{ question.question_text }}</p>
    <p>Создано: {{ question.date_created }}</p>
    {% if user.is_authenticated %}
      <button class="btn btn-link">
        <a href="{% url 'answer_create' question.id %}">Ответить</a>
      </button>
    {% endif %}
</div>

<h2>Ответы</h2>
<ul>
  {% for answer in question.answer_set.all %}
    {% if answer.permission %}
      <section>
        {{ answer.user }}
        {{ answer.date_created }}
        <li>{{ answer.answer_text }}</li>
      </section>
    {% endif %}
  {% empty %}
    <li>Ответов еще нету.</li>
  {% endfor %}
</ul>
{% endblock %}